server:
  servlet:
    context-path: /api
  port: 9999

spring:
  datasource:
    name: db
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_sample
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: mapper/*.xml


logging:
  level:
    com.neusoft.springboot.dao.mapper: debug